#!/usr/bin/env python3
"""Generate docs/PROBE_CATALOG.md from the probe library.

python scripts/gen_probe_docs.py           # rewrite the file
python scripts/gen_probe_docs.py --check   # exit 1 if it is out of date (used by the tests)
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

from scanner.models import Category, Severity
from scanner.probes import Probe, load_probes
from scanner.taxonomy import ATLAS_TECHNIQUES, CATEGORIES, OWASP_EDITION, OWASP_LLM_TOP10

OUT = Path(__file__).resolve().parents[1] / "docs" / "PROBE_CATALOG.md"

# OWASP items a prompt-level, black-box scanner cannot meaningfully test. Said plainly in the docs.
NOT_COVERED = {
    "LLM03": "Supply chain: about model, dataset and dependency provenance, not about what an endpoint does when prompted.",
    "LLM04": "Data and model poisoning at training time cannot be tested through an inference endpoint. (RAG poisoning at retrieval time is covered under LLM08.)",
    "LLM09": "Misinformation needs ground truth for the application's domain; use an evaluation framework with your own reference answers.",
    "LLM10": "Unbounded consumption is a load and quota test. llmscan deliberately rate-limits itself and does not try to exhaust a target.",
}


def criteria(p: Probe) -> str:
    c = p.success_criteria
    kinds = sorted({r.type for r in c.rules})
    if c.judge is not None:
        kinds.append("judge")
    return ", ".join(kinds) or "-"


def escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render(probes: list[Probe]) -> str:
    by_cat: dict[Category, list[Probe]] = defaultdict(list)
    for p in probes:
        by_cat[p.category].append(p)
    out: list[str] = [
        "# Probe catalogue",
        "",
        "<!-- Generated by scripts/gen_probe_docs.py from probes/. Do not edit by hand. -->",
        "",
        f"{len(probes)} built-in probes in {len(by_cat)} categories. Every probe carries OWASP LLM Top 10 "
        f"({OWASP_EDITION}) and MITRE ATLAS tags, a success criterion and remediation guidance. "
        "The probe format is defined by [`probes/probe.schema.json`](../probes/probe.schema.json).",
        "",
        "## Coverage at a glance",
        "",
        "| Category | Probes | Critical | High | Medium | Low | OWASP LLM Top 10 | MITRE ATLAS |",
        "|---|---:|---:|---:|---:|---:|---|---|",
    ]
    for cat in Category:
        items = by_cat.get(cat, [])
        sev = Counter(p.severity for p in items)
        info = CATEGORIES[cat]
        out.append(
            f"| [{info.title}](#{info.title.lower().replace(' ', '-')}) | {len(items)} | "
            f"{sev[Severity.CRITICAL]} | {sev[Severity.HIGH]} | {sev[Severity.MEDIUM]} | {sev[Severity.LOW]} | "
            f"{', '.join(info.owasp)} | {', '.join(info.atlas)} |"
        )
    out += [
        "",
        "## OWASP LLM Top 10 coverage",
        "",
        "| ID | Risk | Probes | Notes |",
        "|---|---|---:|---|",
    ]
    owasp_count = Counter(o for p in probes for o in p.owasp)
    for oid, name in OWASP_LLM_TOP10.items():
        n = owasp_count.get(oid, 0)
        note = "covered" if n else NOT_COVERED.get(oid, "not covered")
        out.append(f"| {oid} | {name} | {n} | {note} |")
    atlas_count = Counter(a for p in probes for a in p.atlas)
    out += [
        "",
        "## MITRE ATLAS techniques exercised",
        "",
        "| Technique | Name | Probes |",
        "|---|---|---:|",
    ]
    for tid in sorted(atlas_count):
        out.append(
            f"| [{tid}](https://atlas.mitre.org/techniques/{tid}) | {escape(ATLAS_TECHNIQUES.get(tid, ''))} | {atlas_count[tid]} |"
        )

    for cat in Category:
        info = CATEGORIES[cat]
        out += ["", f"## {info.title}", "", info.description, ""]
        out += [
            "| ID | Probe | Severity | Kind | OWASP | ATLAS | Detected by |",
            "|---|---|---|---|---|---|---|",
        ]
        for p in sorted(by_cat.get(cat, []), key=lambda x: x.id):
            out.append(
                f"| `{p.id}` | {escape(p.name)} | {p.severity.value} | {p.kind} | {', '.join(p.owasp)} | "
                f"{', '.join(p.atlas)} | {criteria(p)} |"
            )
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check", action="store_true", help="fail if the file is stale instead of rewriting it"
    )
    args = ap.parse_args()
    text = render(load_probes())
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(
                f"{OUT.name} is out of date: run `python scripts/gen_probe_docs.py`",
                file=sys.stderr,
            )
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
